// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type MentionlegaleDocumentDataSlicesSlice = LegalInformationSlice;

/**
 * Content for MentionLegale documents
 */
interface MentionlegaleDocumentData {
  /**
   * Title field in *MentionLegale*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Mentionlegale.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *MentionLegale*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: Mentionlegale.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MentionlegaleDocumentDataSlicesSlice> /**
   * Meta Title field in *MentionLegale*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: Mentionlegale.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *MentionLegale*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: Mentionlegale.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *MentionLegale*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Mentionlegale.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * MentionLegale document from Prismic
 *
 * - **API ID**: `Mentionlegale`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MentionlegaleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MentionlegaleDocumentData>,
    "Mentionlegale",
    Lang
  >;

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for article documents
 */
interface ArticleDocumentData {
  /**
   * articleImage field in *article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.articleimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  articleimage: prismic.ImageField<never>;

  /**
   * ArticleTitle field in *article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.articletitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  articletitle: prismic.RichTextField;

  /**
   * articleDescription field in *article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.articledescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  articledescription: prismic.RichTextField;

  /**
   * Date de publication field in *article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Ajouter la date du numéro
   * - **API ID Path**: article.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * pdf field in *article*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: entrer le pdf
   * - **API ID Path**: article.pdf
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pdf: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Abstract field in *article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.abstract
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  abstract: prismic.RichTextField;

  /**
   * Slice Zone field in *article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type GlossaireDocumentDataSlicesSlice = SplitTitleDescriptionSlice;

/**
 * Content for glossaire documents
 */
interface GlossaireDocumentData {
  /**
   * Slice Zone field in *glossaire*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: glossaire.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GlossaireDocumentDataSlicesSlice> /**
   * Meta Title field in *glossaire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: glossaire.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *glossaire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: glossaire.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *glossaire*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: glossaire.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * glossaire document from Prismic
 *
 * - **API ID**: `glossaire`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlossaireDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GlossaireDocumentData>,
    "glossaire",
    Lang
  >;

/**
 * Item in *Homepage → articleItem*
 */
export interface HomepageDocumentDataArticleitemItem {
  /**
   * articles field in *Homepage → articleItem*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.articleitem[].articles
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articles: prismic.ContentRelationshipField<"article">;
}

type HomepageDocumentDataSlicesSlice =
  | ArticlesInjectSlice
  | IntroTextVisualsSlice
  | TwoColumnPoemLayoutSlice
  | FooterSimpleGridSlice
  | NavigationBarSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * articleDetail field in *Homepage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.articledetail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articledetail: prismic.ContentRelationshipField<"article">;

  /**
   * articleItem field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.articleitem[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articleitem: prismic.GroupField<
    Simplify<HomepageDocumentDataArticleitemItem>
  >;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = NavigationBarSlice;

/**
 * Content for navigation documents
 */
interface NavigationDocumentData {
  /**
   * Slice Zone field in *navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageTitleDocumentDataSlicesSlice = never;

/**
 * Content for Page_title documents
 */
interface PageTitleDocumentData {
  /**
   * Slice Zone field in *Page_title*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page_title.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageTitleDocumentDataSlicesSlice>;
}

/**
 * Page_title document from Prismic
 *
 * - **API ID**: `page_title`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageTitleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PageTitleDocumentData>,
    "page_title",
    Lang
  >;

type SengagerDocumentDataSlicesSlice = InfoColumnsSlice;

/**
 * Content for sengager documents
 */
interface SengagerDocumentData {
  /**
   * Title field in *sengager*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sengager.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *sengager*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sengager.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SengagerDocumentDataSlicesSlice> /**
   * Meta Title field in *sengager*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sengager.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *sengager*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sengager.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *sengager*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sengager.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * sengager document from Prismic
 *
 * - **API ID**: `sengager`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SengagerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SengagerDocumentData>,
    "sengager",
    Lang
  >;

/**
 * Item in *Header → Navigation*
 */
export interface SitetitleDocumentDataNavigationItem {
  /**
   * link field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface SitetitleDocumentData {
  /**
   * titre du site field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.titre_du_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_du_site: prismic.KeyTextField;

  /**
   * Meta description field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SitetitleDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `sitetitle`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SitetitleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SitetitleDocumentData>,
    "sitetitle",
    Lang
  >;

export type AllDocumentTypes =
  | MentionlegaleDocument
  | ArticleDocument
  | GlossaireDocument
  | HomepageDocument
  | NavigationDocument
  | PageTitleDocument
  | SengagerDocument
  | SitetitleDocument;

/**
 * Default variation for ArticlesInject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesInjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ArticlesInject*
 */
type ArticlesInjectSliceVariation = ArticlesInjectSliceDefault;

/**
 * ArticlesInject Shared Slice
 *
 * - **API ID**: `articles_inject`
 * - **Description**: ArticlesInject
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticlesInjectSlice = prismic.SharedSlice<
  "articles_inject",
  ArticlesInjectSliceVariation
>;

/**
 * Primary content in *Button → button → Primary*
 */
export interface CtaSliceSimplePrimary {
  /**
   * Button Text field in *Button → button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.simple.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Button → button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.simple.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * button variation for Button Slice
 *
 * - **API ID**: `simple`
 * - **Description**: A single call-to-action button with customizable text and link.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceSimple = prismic.SharedSliceVariation<
  "simple",
  Simplify<CtaSliceSimplePrimary>,
  never
>;

/**
 * Slice variation for *Button*
 */
type CtaSliceVariation = CtaSliceSimple;

/**
 * Button Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *FooterSimpleGrid → Default → Primary → Liens du plan du site*
 */
export interface FooterSimpleGridSliceDefaultPrimaryLinksItem {
  /**
   * Label du lien field in *FooterSimpleGrid → Default → Primary → Liens du plan du site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ACCUEIL
   * - **API ID Path**: footer_simple_grid.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * URL du lien field in *FooterSimpleGrid → Default → Primary → Liens du plan du site*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /
   * - **API ID Path**: footer_simple_grid.default.primary.links[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *FooterSimpleGrid → Default → Primary → Liens légaux*
 */
export interface FooterSimpleGridSliceDefaultPrimaryFooterLinksItem {
  /**
   * Label du lien field in *FooterSimpleGrid → Default → Primary → Liens légaux*
   *
   * - **Field Type**: Text
   * - **Placeholder**: POLITIQUE DE CONFIDENTIALITÉ
   * - **API ID Path**: footer_simple_grid.default.primary.footer_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * URL du lien field in *FooterSimpleGrid → Default → Primary → Liens légaux*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /politique-confidentialite
   * - **API ID Path**: footer_simple_grid.default.primary.footer_links[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *FooterSimpleGrid → Default → Primary*
 */
export interface FooterSimpleGridSliceDefaultPrimary {
  /**
   * Email field in *FooterSimpleGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: contact@example.com
   * - **API ID Path**: footer_simple_grid.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Téléphone field in *FooterSimpleGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +33 6 89 69 21 14
   * - **API ID Path**: footer_simple_grid.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Copyright field in *FooterSimpleGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ©2025 BUG
   * - **API ID Path**: footer_simple_grid.default.primary.copyright
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;

  /**
   * Liens du plan du site field in *FooterSimpleGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<
    Simplify<FooterSimpleGridSliceDefaultPrimaryLinksItem>
  >;

  /**
   * Liens légaux field in *FooterSimpleGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.footer_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_links: prismic.GroupField<
    Simplify<FooterSimpleGridSliceDefaultPrimaryFooterLinksItem>
  >;
}

/**
 * Default variation for FooterSimpleGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default footer layout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSimpleGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSimpleGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FooterSimpleGrid*
 */
type FooterSimpleGridSliceVariation = FooterSimpleGridSliceDefault;

/**
 * FooterSimpleGrid Shared Slice
 *
 * - **API ID**: `footer_simple_grid`
 * - **Description**: Footer with grid layout containing site map, contact info, social media and legal links
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSimpleGridSlice = prismic.SharedSlice<
  "footer_simple_grid",
  FooterSimpleGridSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Visual field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  visual: prismic.ImageField<never>;

  /**
   * article field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.article
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *InfoColumns → card-sengager → Primary → EngagementGroup*
 */
export interface InfoColumnsSliceAudienceTiersPrimaryEngagementgroupItem {
  /**
   * EngagementContent field in *InfoColumns → card-sengager → Primary → EngagementGroup*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_columns.audience_tiers.primary.engagementgroup[].engagementcontent
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  engagementcontent: prismic.RichTextField;
}

/**
 * Primary content in *InfoColumns → card-sengager → Primary*
 */
export interface InfoColumnsSliceAudienceTiersPrimary {
  /**
   * Main Title field in *InfoColumns → card-sengager → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: info_columns.audience_tiers.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * EngamentSubtitle field in *InfoColumns → card-sengager → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_columns.audience_tiers.primary.engamentsubtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  engamentsubtitle: prismic.RichTextField;

  /**
   * EngagementGroup field in *InfoColumns → card-sengager → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: info_columns.audience_tiers.primary.engagementgroup[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  engagementgroup: prismic.GroupField<
    Simplify<InfoColumnsSliceAudienceTiersPrimaryEngagementgroupItem>
  >;
}

/**
 * card-sengager variation for InfoColumns Slice
 *
 * - **API ID**: `audience_tiers`
 * - **Description**: Displays structured information for several types of audience or scenarios, typically with a heading, description, and possibly contact information for each.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoColumnsSliceAudienceTiers = prismic.SharedSliceVariation<
  "audience_tiers",
  Simplify<InfoColumnsSliceAudienceTiersPrimary>,
  never
>;

/**
 * Slice variation for *InfoColumns*
 */
type InfoColumnsSliceVariation = InfoColumnsSliceAudienceTiers;

/**
 * InfoColumns Shared Slice
 *
 * - **API ID**: `info_columns`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoColumnsSlice = prismic.SharedSlice<
  "info_columns",
  InfoColumnsSliceVariation
>;

/**
 * Item in *AproposSection → Default → Primary → Secondary Visual Blocks*
 */
export interface IntroTextVisualsSliceDefaultPrimarySecondaryVisualsItem {
  /**
   * Image field in *AproposSection → Default → Primary → Secondary Visual Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.secondary_visuals[].secondary_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  secondary_image: prismic.ImageField<never>;

  /**
   * Text field in *AproposSection → Default → Primary → Secondary Visual Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.secondary_visuals[].secondary_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_text: prismic.RichTextField;
}

/**
 * Primary content in *AproposSection → Default → Primary*
 */
export interface IntroTextVisualsSliceDefaultPrimary {
  /**
   * Title field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Main Rich Text Block field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.main_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_text: prismic.RichTextField;

  /**
   * Main Visual field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.main_visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_visual: prismic.ImageField<never>;

  /**
   * Secondary Visual Blocks field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.secondary_visuals[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  secondary_visuals: prismic.GroupField<
    Simplify<IntroTextVisualsSliceDefaultPrimarySecondaryVisualsItem>
  >;
}

/**
 * Default variation for AproposSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout featuring a heading, main text, supporting images, and additional explanatory content.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextVisualsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroTextVisualsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AproposSection*
 */
type IntroTextVisualsSliceVariation = IntroTextVisualsSliceDefault;

/**
 * AproposSection Shared Slice
 *
 * - **API ID**: `intro_text_visuals`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextVisualsSlice = prismic.SharedSlice<
  "intro_text_visuals",
  IntroTextVisualsSliceVariation
>;

/**
 * Item in *LegalInformation → Default → Primary → Info Items*
 */
export interface LegalInformationSliceDefaultPrimaryInfoItemsItem {
  /**
   * label field in *LegalInformation → Default → Primary → Info Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_information.default.primary.info_items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * value field in *LegalInformation → Default → Primary → Info Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_information.default.primary.info_items[].value
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  value: prismic.RichTextField;
}

/**
 * Primary content in *LegalInformation → Default → Primary*
 */
export interface LegalInformationSliceDefaultPrimary {
  /**
   * Heading field in *LegalInformation → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_information.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.TitleField;

  /**
   * Info Items field in *LegalInformation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: legal_information.default.primary.info_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  info_items: prismic.GroupField<
    Simplify<LegalInformationSliceDefaultPrimaryInfoItemsItem>
  >;
}

/**
 * Default variation for LegalInformation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays legal information with a heading and key/value pairs for different required data items.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalInformationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LegalInformationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LegalInformation*
 */
type LegalInformationSliceVariation = LegalInformationSliceDefault;

/**
 * LegalInformation Shared Slice
 *
 * - **API ID**: `legal_information`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LegalInformationSlice = prismic.SharedSlice<
  "legal_information",
  LegalInformationSliceVariation
>;

/**
 * Item in *NavigationBar → Default → Primary → Left Links*
 */
export interface NavigationBarSliceDefaultPrimaryLeftLinksItem {
  /**
   * Link field in *NavigationBar → Default → Primary → Left Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.left_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *NavigationBar → Default → Primary → Right Links*
 */
export interface NavigationBarSliceDefaultPrimaryRightLinksItem {
  /**
   * Link field in *NavigationBar → Default → Primary → Right Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.right_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *NavigationBar → Default → Primary*
 */
export interface NavigationBarSliceDefaultPrimary {
  /**
   * Left Links field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.left_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  left_links: prismic.GroupField<
    Simplify<NavigationBarSliceDefaultPrimaryLeftLinksItem>
  >;

  /**
   * Center Title field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.center_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  center_title: prismic.TitleField;

  /**
   * Right Links field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.right_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  right_links: prismic.GroupField<
    Simplify<NavigationBarSliceDefaultPrimaryRightLinksItem>
  >;
}

/**
 * Default variation for NavigationBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard horizontal navigation bar with a central main link and multiple links to the left and right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationBar*
 */
type NavigationBarSliceVariation = NavigationBarSliceDefault;

/**
 * NavigationBar Shared Slice
 *
 * - **API ID**: `navigation_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationBarSlice = prismic.SharedSlice<
  "navigation_bar",
  NavigationBarSliceVariation
>;

/**
 * Primary content in *GlossaireItem → Default → Primary*
 */
export interface SplitTitleDescriptionSliceDefaultPrimary {
  /**
   * GlossaireItemTitle field in *GlossaireItem → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: split_title_description.default.primary.GlossaireItemTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  GlossaireItemTitle: prismic.TitleField;

  /**
   * GlossaireItemDescription field in *GlossaireItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_title_description.default.primary.GlossaireItemDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  GlossaireItemDescription: prismic.RichTextField;
}

/**
 * Default variation for GlossaireItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard split layout with a large title and a body of descriptive text.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitTitleDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitTitleDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GlossaireItem*
 */
type SplitTitleDescriptionSliceVariation = SplitTitleDescriptionSliceDefault;

/**
 * GlossaireItem Shared Slice
 *
 * - **API ID**: `split_title_description`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitTitleDescriptionSlice = prismic.SharedSlice<
  "split_title_description",
  SplitTitleDescriptionSliceVariation
>;

/**
 * Primary content in *Card → card → Primary*
 */
export interface TwoColumnPoemLayoutSlicePoemWithMetadataAndTitlePrimary {
  /**
   * articleImage field in *Card → card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.articleimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  articleimage: prismic.ImageField<never>;

  /**
   * ArticleTitle field in *Card → card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.right_column_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  right_column_content: prismic.RichTextField;

  /**
   * articleNumber field in *Card → card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.articlenumber
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  articlenumber: prismic.RichTextField;

  /**
   * articleDetail field in *Card → card → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.articledetail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articledetail: prismic.ContentRelationshipField<"article">;
}

/**
 * card variation for Card Slice
 *
 * - **API ID**: `poem_with_metadata_and_title`
 * - **Description**: This variation includes a left column for poem/prose title and metadata, and a right column for the main poetic content, suitable for literary publications.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnPoemLayoutSlicePoemWithMetadataAndTitle =
  prismic.SharedSliceVariation<
    "poem_with_metadata_and_title",
    Simplify<TwoColumnPoemLayoutSlicePoemWithMetadataAndTitlePrimary>,
    never
  >;

/**
 * Slice variation for *Card*
 */
type TwoColumnPoemLayoutSliceVariation =
  TwoColumnPoemLayoutSlicePoemWithMetadataAndTitle;

/**
 * Card Shared Slice
 *
 * - **API ID**: `two_column_poem_layout`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnPoemLayoutSlice = prismic.SharedSlice<
  "two_column_poem_layout",
  TwoColumnPoemLayoutSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MentionlegaleDocument,
      MentionlegaleDocumentData,
      MentionlegaleDocumentDataSlicesSlice,
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      GlossaireDocument,
      GlossaireDocumentData,
      GlossaireDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataArticleitemItem,
      HomepageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageTitleDocument,
      PageTitleDocumentData,
      PageTitleDocumentDataSlicesSlice,
      SengagerDocument,
      SengagerDocumentData,
      SengagerDocumentDataSlicesSlice,
      SitetitleDocument,
      SitetitleDocumentData,
      SitetitleDocumentDataNavigationItem,
      AllDocumentTypes,
      ArticlesInjectSlice,
      ArticlesInjectSliceVariation,
      ArticlesInjectSliceDefault,
      CtaSlice,
      CtaSliceSimplePrimary,
      CtaSliceVariation,
      CtaSliceSimple,
      FooterSimpleGridSlice,
      FooterSimpleGridSliceDefaultPrimaryLinksItem,
      FooterSimpleGridSliceDefaultPrimaryFooterLinksItem,
      FooterSimpleGridSliceDefaultPrimary,
      FooterSimpleGridSliceVariation,
      FooterSimpleGridSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InfoColumnsSlice,
      InfoColumnsSliceAudienceTiersPrimaryEngagementgroupItem,
      InfoColumnsSliceAudienceTiersPrimary,
      InfoColumnsSliceVariation,
      InfoColumnsSliceAudienceTiers,
      IntroTextVisualsSlice,
      IntroTextVisualsSliceDefaultPrimarySecondaryVisualsItem,
      IntroTextVisualsSliceDefaultPrimary,
      IntroTextVisualsSliceVariation,
      IntroTextVisualsSliceDefault,
      LegalInformationSlice,
      LegalInformationSliceDefaultPrimaryInfoItemsItem,
      LegalInformationSliceDefaultPrimary,
      LegalInformationSliceVariation,
      LegalInformationSliceDefault,
      NavigationBarSlice,
      NavigationBarSliceDefaultPrimaryLeftLinksItem,
      NavigationBarSliceDefaultPrimaryRightLinksItem,
      NavigationBarSliceDefaultPrimary,
      NavigationBarSliceVariation,
      NavigationBarSliceDefault,
      SplitTitleDescriptionSlice,
      SplitTitleDescriptionSliceDefaultPrimary,
      SplitTitleDescriptionSliceVariation,
      SplitTitleDescriptionSliceDefault,
      TwoColumnPoemLayoutSlice,
      TwoColumnPoemLayoutSlicePoemWithMetadataAndTitlePrimary,
      TwoColumnPoemLayoutSliceVariation,
      TwoColumnPoemLayoutSlicePoemWithMetadataAndTitle,
    };
  }
}
