// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for article documents
 */
interface ArticleDocumentData {
  /**
   * articleImage field in *article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.articleimage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  articleimage: prismic.ImageField<never>;

  /**
   * ArticleTitle field in *article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.articletitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  articletitle: prismic.RichTextField;

  /**
   * articleDescription field in *article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.articledescription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  articledescription: prismic.RichTextField;

  /**
   * Date de publication field in *article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Ajouter la date du numéro
   * - **API ID Path**: article.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Slice Zone field in *article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Title field in *article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type GlossaireDocumentDataSlicesSlice = SplitTitleDescriptionSlice;

/**
 * Content for glossaire documents
 */
interface GlossaireDocumentData {
  /**
   * Slice Zone field in *glossaire*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: glossaire.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GlossaireDocumentDataSlicesSlice> /**
   * Meta Title field in *glossaire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: glossaire.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *glossaire*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: glossaire.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *glossaire*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: glossaire.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * glossaire document from Prismic
 *
 * - **API ID**: `glossaire`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GlossaireDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<GlossaireDocumentData>,
    "glossaire",
    Lang
  >;

/**
 * Item in *Homepage → articleItem*
 */
export interface HomepageDocumentDataArticleitemItem {
  /**
   * articles field in *Homepage → articleItem*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.articleitem[].articles
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articles: prismic.ContentRelationshipField<"article">;
}

type HomepageDocumentDataSlicesSlice =
  | IntroTextVisualsSlice
  | ArticleReferenceSlice
  | TwoColumnPoemLayoutSlice
  | FooterSimpleGridSlice
  | NavigationBarSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * articleDetail field in *Homepage*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.articledetail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articledetail: prismic.ContentRelationshipField<"article">;

  /**
   * articleItem field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.articleitem[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  articleitem: prismic.GroupField<
    Simplify<HomepageDocumentDataArticleitemItem>
  >;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Header → Navigation*
 */
export interface SitetitleDocumentDataNavigationItem {
  /**
   * link field in *Header → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface SitetitleDocumentData {
  /**
   * titre du site field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.titre_du_site
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre_du_site: prismic.KeyTextField;

  /**
   * Meta description field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sitetitle.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SitetitleDocumentDataNavigationItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `sitetitle`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SitetitleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SitetitleDocumentData>,
    "sitetitle",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | GlossaireDocument
  | HomepageDocument
  | SitetitleDocument;

/**
 * Item in *ArticleReference → Default → Primary → article*
 */
export interface ArticleReferenceSliceDefaultPrimaryArticleItem {
  /**
   * articlePage field in *ArticleReference → Default → Primary → article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article_reference.default.primary.article[].articlepage
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articlepage: prismic.ContentRelationshipField<"article">;
}

/**
 * Primary content in *ArticleReference → Default → Primary*
 */
export interface ArticleReferenceSliceDefaultPrimary {
  /**
   * article field in *ArticleReference → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article_reference.default.primary.article[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  article: prismic.GroupField<
    Simplify<ArticleReferenceSliceDefaultPrimaryArticleItem>
  >;
}

/**
 * Default variation for ArticleReference Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleReferenceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleReferenceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleReference*
 */
type ArticleReferenceSliceVariation = ArticleReferenceSliceDefault;

/**
 * ArticleReference Shared Slice
 *
 * - **API ID**: `article_reference`
 * - **Description**: ArticleReference
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleReferenceSlice = prismic.SharedSlice<
  "article_reference",
  ArticleReferenceSliceVariation
>;

/**
 * Primary content in *Button → button → Primary*
 */
export interface CtaSliceSimplePrimary {
  /**
   * Button Text field in *Button → button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.simple.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Button → button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.simple.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * button variation for Button Slice
 *
 * - **API ID**: `simple`
 * - **Description**: A single call-to-action button with customizable text and link.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceSimple = prismic.SharedSliceVariation<
  "simple",
  Simplify<CtaSliceSimplePrimary>,
  never
>;

/**
 * Slice variation for *Button*
 */
type CtaSliceVariation = CtaSliceSimple;

/**
 * Button Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Footer → Default → Primary → Navigation and Contact Links*
 */
export interface FooterSimpleGridSliceDefaultPrimaryLinksItem {
  /**
   * Label field in *Footer → Default → Primary → Navigation and Contact Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * URL field in *Footer → Default → Primary → Navigation and Contact Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.links[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Default → Primary → Social Icons*
 */
export interface FooterSimpleGridSliceDefaultPrimarySocialsItem {
  /**
   * Platform field in *Footer → Default → Primary → Social Icons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.socials[].platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  platform: prismic.SelectField<"instagram" | "facebook" | "youtube">;

  /**
   * URL field in *Footer → Default → Primary → Social Icons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.socials[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSimpleGridSliceDefaultPrimary {
  /**
   * Main Message field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.main_message
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_message: prismic.RichTextField;

  /**
   * Navigation and Contact Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<
    Simplify<FooterSimpleGridSliceDefaultPrimaryLinksItem>
  >;

  /**
   * Social Icons field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_simple_grid.default.primary.socials[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<
    Simplify<FooterSimpleGridSliceDefaultPrimarySocialsItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Basic three-column footer grid with message, navigation/contact, and social links.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSimpleGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSimpleGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSimpleGridSliceVariation = FooterSimpleGridSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer_simple_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSimpleGridSlice = prismic.SharedSlice<
  "footer_simple_grid",
  FooterSimpleGridSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Visual field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  visual: prismic.ImageField<never>;

  /**
   * article field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.article
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *AproposSection → Default → Primary → Secondary Visual Blocks*
 */
export interface IntroTextVisualsSliceDefaultPrimarySecondaryVisualsItem {
  /**
   * Image field in *AproposSection → Default → Primary → Secondary Visual Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.secondary_visuals[].secondary_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  secondary_image: prismic.ImageField<never>;

  /**
   * Text field in *AproposSection → Default → Primary → Secondary Visual Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.secondary_visuals[].secondary_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_text: prismic.RichTextField;
}

/**
 * Primary content in *AproposSection → Default → Primary*
 */
export interface IntroTextVisualsSliceDefaultPrimary {
  /**
   * Title field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Main Rich Text Block field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.main_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_text: prismic.RichTextField;

  /**
   * Main Visual field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.main_visual
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_visual: prismic.ImageField<never>;

  /**
   * Secondary Visual Blocks field in *AproposSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: intro_text_visuals.default.primary.secondary_visuals[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  secondary_visuals: prismic.GroupField<
    Simplify<IntroTextVisualsSliceDefaultPrimarySecondaryVisualsItem>
  >;
}

/**
 * Default variation for AproposSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout featuring a heading, main text, supporting images, and additional explanatory content.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextVisualsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroTextVisualsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AproposSection*
 */
type IntroTextVisualsSliceVariation = IntroTextVisualsSliceDefault;

/**
 * AproposSection Shared Slice
 *
 * - **API ID**: `intro_text_visuals`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroTextVisualsSlice = prismic.SharedSlice<
  "intro_text_visuals",
  IntroTextVisualsSliceVariation
>;

/**
 * Item in *NavigationBar → Default → Primary → Left Links*
 */
export interface NavigationBarSliceDefaultPrimaryLeftLinksItem {
  /**
   * Link field in *NavigationBar → Default → Primary → Left Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.left_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *NavigationBar → Default → Primary → Right Links*
 */
export interface NavigationBarSliceDefaultPrimaryRightLinksItem {
  /**
   * Link field in *NavigationBar → Default → Primary → Right Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.right_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *NavigationBar → Default → Primary*
 */
export interface NavigationBarSliceDefaultPrimary {
  /**
   * Left Links field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.left_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  left_links: prismic.GroupField<
    Simplify<NavigationBarSliceDefaultPrimaryLeftLinksItem>
  >;

  /**
   * Center Title field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.center_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  center_title: prismic.TitleField;

  /**
   * Right Links field in *NavigationBar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_bar.default.primary.right_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  right_links: prismic.GroupField<
    Simplify<NavigationBarSliceDefaultPrimaryRightLinksItem>
  >;
}

/**
 * Default variation for NavigationBar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard horizontal navigation bar with a central main link and multiple links to the left and right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationBarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationBarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationBar*
 */
type NavigationBarSliceVariation = NavigationBarSliceDefault;

/**
 * NavigationBar Shared Slice
 *
 * - **API ID**: `navigation_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationBarSlice = prismic.SharedSlice<
  "navigation_bar",
  NavigationBarSliceVariation
>;

/**
 * Primary content in *GlossaireItem → Default → Primary*
 */
export interface SplitTitleDescriptionSliceDefaultPrimary {
  /**
   * GlossaireItemTitle field in *GlossaireItem → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: split_title_description.default.primary.GlossaireItemTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  GlossaireItemTitle: prismic.TitleField;

  /**
   * GlossaireItemDescription field in *GlossaireItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: split_title_description.default.primary.GlossaireItemDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  GlossaireItemDescription: prismic.RichTextField;
}

/**
 * Default variation for GlossaireItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard split layout with a large title and a body of descriptive text.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitTitleDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SplitTitleDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GlossaireItem*
 */
type SplitTitleDescriptionSliceVariation = SplitTitleDescriptionSliceDefault;

/**
 * GlossaireItem Shared Slice
 *
 * - **API ID**: `split_title_description`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SplitTitleDescriptionSlice = prismic.SharedSlice<
  "split_title_description",
  SplitTitleDescriptionSliceVariation
>;

/**
 * Primary content in *Card → card → Primary*
 */
export interface TwoColumnPoemLayoutSlicePoemWithMetadataAndTitlePrimary {
  /**
   * articleImage field in *Card → card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.articleimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  articleimage: prismic.ImageField<never>;

  /**
   * ArticleTitle field in *Card → card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.right_column_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  right_column_content: prismic.RichTextField;

  /**
   * articleNumber field in *Card → card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.articlenumber
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  articlenumber: prismic.RichTextField;

  /**
   * articleDetail field in *Card → card → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_poem_layout.poem_with_metadata_and_title.primary.articledetail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  articledetail: prismic.ContentRelationshipField<"article">;
}

/**
 * card variation for Card Slice
 *
 * - **API ID**: `poem_with_metadata_and_title`
 * - **Description**: This variation includes a left column for poem/prose title and metadata, and a right column for the main poetic content, suitable for literary publications.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnPoemLayoutSlicePoemWithMetadataAndTitle =
  prismic.SharedSliceVariation<
    "poem_with_metadata_and_title",
    Simplify<TwoColumnPoemLayoutSlicePoemWithMetadataAndTitlePrimary>,
    never
  >;

/**
 * Slice variation for *Card*
 */
type TwoColumnPoemLayoutSliceVariation =
  TwoColumnPoemLayoutSlicePoemWithMetadataAndTitle;

/**
 * Card Shared Slice
 *
 * - **API ID**: `two_column_poem_layout`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnPoemLayoutSlice = prismic.SharedSlice<
  "two_column_poem_layout",
  TwoColumnPoemLayoutSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      GlossaireDocument,
      GlossaireDocumentData,
      GlossaireDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataArticleitemItem,
      HomepageDocumentDataSlicesSlice,
      SitetitleDocument,
      SitetitleDocumentData,
      SitetitleDocumentDataNavigationItem,
      AllDocumentTypes,
      ArticleReferenceSlice,
      ArticleReferenceSliceDefaultPrimaryArticleItem,
      ArticleReferenceSliceDefaultPrimary,
      ArticleReferenceSliceVariation,
      ArticleReferenceSliceDefault,
      CtaSlice,
      CtaSliceSimplePrimary,
      CtaSliceVariation,
      CtaSliceSimple,
      FooterSimpleGridSlice,
      FooterSimpleGridSliceDefaultPrimaryLinksItem,
      FooterSimpleGridSliceDefaultPrimarySocialsItem,
      FooterSimpleGridSliceDefaultPrimary,
      FooterSimpleGridSliceVariation,
      FooterSimpleGridSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      IntroTextVisualsSlice,
      IntroTextVisualsSliceDefaultPrimarySecondaryVisualsItem,
      IntroTextVisualsSliceDefaultPrimary,
      IntroTextVisualsSliceVariation,
      IntroTextVisualsSliceDefault,
      NavigationBarSlice,
      NavigationBarSliceDefaultPrimaryLeftLinksItem,
      NavigationBarSliceDefaultPrimaryRightLinksItem,
      NavigationBarSliceDefaultPrimary,
      NavigationBarSliceVariation,
      NavigationBarSliceDefault,
      SplitTitleDescriptionSlice,
      SplitTitleDescriptionSliceDefaultPrimary,
      SplitTitleDescriptionSliceVariation,
      SplitTitleDescriptionSliceDefault,
      TwoColumnPoemLayoutSlice,
      TwoColumnPoemLayoutSlicePoemWithMetadataAndTitlePrimary,
      TwoColumnPoemLayoutSliceVariation,
      TwoColumnPoemLayoutSlicePoemWithMetadataAndTitle,
    };
  }
}
